//Database to set the object once payment is fully successful
export const SET_PURCHASE_TOKEN_REQUEST_REQUEST = "SET_PURCHASE_TOKEN_REQUEST_REQUEST"; 
export const SET_PURCHASE_TOKEN_REQUEST_SUCCESS = "SET_PURCHASE_TOKEN_REQUEST_SUCCESS";
export const SET_PURCHASE_TOKEN_REQUEST_FAILURE = "SET_PURCHASE_TOKEN_REQUEST_FAILURE";

//Database to set the purchase token when payment is pending 
export const SET_PENDING_PURCHASE_TOKEN_REQUEST = "SET_PENDING_PURCHASE_TOKEN_REQUEST";
export const SET_PENDING_PURCHASE_TOKEN_REQUEST_SUCCESS = "SET_PENDING_PURCHASE_TOKEN_REQUEST_SUCCESS";
export const SET_PENDING_PURCHASE_TOKEN_REQUEST_FAILURE = "SET_PENDING_PURCHASE_TOKEN_REQUEST_FAILURE";

//Database to get the purchase token when payment is pending 
export const GET_PENDING_PURCHASE_TOKEN_REQUEST = "GET_PENDING_PURCHASE_TOKEN_REQUEST";
export const GET_PENDING_PURCHASE_TOKEN_REQUEST_SUCCESS = "GET_PENDING_PURCHASE_TOKEN_REQUEST_SUCCESS";
export const GET_PENDING_PURCHASE_TOKEN_REQUEST_FAILURE = "GET_PENDING_PURCHASE_TOKEN_REQUEST_FAILURE";